spring:
  mvc: #配置页面访问
    view:
      prefix: classpath:/templates/ #前缀
      suffix: .* #后缀
  datasource: #配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: root
    password: root

  devtools:
    restart:
      enabled: true #开启热部署
  freemarker:
    cache: false #关闭缓存
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
pagehelper:
  helper-dialect: mysql #指定分页插件使用哪种方言
  reasonable: true #设置分页参数的合理化，当pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页。
#  support-methods-arguments: true #支持通过 Mapper 接口参数来传递分页参数

